version: 0.2

env:
  variables:
    ECR_REPOSITORY_URI: $ECR_REPOSITORY_URI
    CONTAINER_NAME: $CONTAINER_NAME

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $ECR_REPOSITORY_URI:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Tagging the Docker image...
      - docker tag $ECR_REPOSITORY_URI:latest $ECR_REPOSITORY_URI:latest
      - echo Pushing the Docker image to ECR...
      - docker push $ECR_REPOSITORY_URI:latest
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' "$CONTAINER_NAME" "$ECR_REPOSITORY_URI:latest" > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
